---
title: "Disease 4 Temp New"
author: "Maliat I"
date: "2023-12-02"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r}
library(tidyverse)
library(ggplot2)
temp4<-read.csv("https://raw.githubusercontent.com/maliat-hossain/FileProcessing/main/Temprature%202019-2021.csv")
disease4_temp<-read.csv("https://raw.githubusercontent.com/maliat-hossain/FileProcessing/main/combined_dataset_disease4.csv")
```

```{r}
head(disease4_temp)
head(temp4)
```
### Converting weekly case count to monthly
```{r}
library(dplyr)

monthly_disease_4 <- disease4_temp %>%
  group_by(Reporting.Area, MMWR.Year, Month = ((MMWR.Week - 1) %% 12) + 1) %>%
  summarize(Monthly_Case_Count = sum(Dengue_Cases_Count))


```
```{r}



```

```{r}
combined_data4 <- temp4 %>%
  inner_join(monthly_disease_4, by = c("Reporting.Area", "year" = "MMWR.Year", "month" = "Month"))
combined_data4 <- combined_data4 %>%
  arrange(Reporting.Area, year, month)
```

```{r}
head(combined_data4)
```

```{r}
correlation <- cor(combined_data4$average_temp, combined_data4$Monthly_Case_Count, use = "complete.obs")
print(correlation)
```

```{r}
library(ggplot2)

# Calculate the correlation matrix
correlation_matrix <- cor(combined_data4[, c("average_temp", "Monthly_Case_Count")], use = "complete.obs")

# Create a dataframe for the correlation matrix
correlation_df <- as.data.frame(correlation_matrix)

# Convert the correlation matrix to long format for ggplot2
library(reshape2)
correlation_df_long <- melt(correlation_df)

# Create a heatmap using ggplot2
ggplot(correlation_df_long, aes(average_temp,Monthly_Case_Count, fill = value)) +
  geom_tile() +
  scale_fill_gradient(low = "blue", high = "red") +
  labs(title = "Correlation Heatmap",
       x = "Variables",
       y = "Variables")

```

```{r}
head(combined_data4)
```

```{r}
state_groups <- combined_data4 %>%
  group_by(Reporting.Area)

# Function to calculate temperature and case count trends for each state
calculate_trends4 <- function(df) {
  # Linear regression for temperature trends
  temp_trend4 <- lm(average_temp ~ year, data = df)  
  
  # Linear regression for case count trends
  case_count_trend <- lm(Monthly_Case_Count ~ year, data = df)
  
  # Calculate slopes for temperature and case count trends
  temp_slope <- coef(temp_trend4)[2]  # Updated to use 'temp_trend3'
  case_count_slope <- coef(case_count_trend)[2]
  
  return(data.frame(Temp_Slope = temp_slope, Case_Count_Slope = case_count_slope))
}

# Apply the calculate_trends function to each state group
trend_results <- state_groups %>%
  do(calculate_trends4(.))
```

```{r}

```

```{r}
print(trend_results)
```

```{r}
filtered_states4 <- trend_results %>%
  filter(Temp_Slope > 0)

# Print the filtered states
print(filtered_states4)
```

